### ISSUE TITLE
Can't build on Win10 32bit

### ISSUE THREAD

**Issue by Zebedee68** [gifnksm/twitter-api-rs#1]
See here: http://stackoverflow.com/questions/32487166/cargo-build-error-file-missing

curl-sys (?) terminates with file missing - same issue here: https://github.com/carllerche/curl-rust/issues/71

**Comment by gifnksm** [comment]
#12 removes curl dependency, so there may be no compilation issue on windows.
If you still have the problem, please feel free to reopen this issue.
