### ISSUE TITLE
upgrade openssl library

### ISSUE THREAD

**Issue by keponk** [gifnksm/twitter-api-rs#16]
Currently this won't build on systems with the newer openssl v1 versions.
Specifically I'm on fedora29 which has `OpenSSL 1.1.1b `, but I' found that this will be an issue with several others. Many soon to follow as they bump this package.

For reference:
https://github.com/sfackler/rust-openssl/issues/1024

**Comment by keponk** [comment]
Agh. I'm still learning the rust process so I've run into some confusion here. 
I'm trying to understand the pipeline here to figure out what's happening and I seem to understand there should be something really simple I could do to run this, like setting some env variable to point at my local openssl library?

Any tips and pointers will be greatly appreciated :)

**Comment by D4nte** [comment]
Hi mate, here is the issue: https://github.com/gifnksm/oauth-client-rs/issues/37

**Comment by gifnksm** [comment]
I'm sorry for being late.

Now, `oauth-client` v0.4.1 released, so this issue should be fixed.

If you still have any problem, please reopen this issue or file a new issue.
