### ISSUE TITLE
Re-export crates needed to use the API

### ISSUE THREAD

**Issue by D4nte** [gifnksm/twitter-api-rs#17]
Currently, consumers of the library need to add the `oauth-client` dependency to their Cargo.toml. This has several downsides:
- tracking/upgrading yet another dependency
- managing conflict if a new version of `oauth-client` is available but `twitter-api` does not support yet. Especially if another deps also depends on `twitter-api`.

Same for the `failure` crate.

Happy to do a PR if I get a concept ACK.

**Comment by gifnksm** [comment]
I'm sorry for being late.

I agree with you. We should re-export the types that are exposed by public API.
Pull Requests are welcome.
