### ISSUE TITLE
Callback URL?

### ISSUE THREAD

**Issue by archae0pteryx** [gifnksm/twitter-api-rs#9]
I haven't explored the recommended oauth read so my question may become obvious in a moment, however, what should the twitter callback URL be if running on localhost?

**Comment by gifnksm** [comment]
I'm sorry for being late.

What does it mean by "running on localhost"?
Does it mean to set up a Twitter clone server on localhost?
Currently, the Twitter API endpoint accesses `twitter.com`, so I think you need to configure `twitter.com` to refer to the Twitter clone by rewriting `/etc/hosts` or something.

This issue has been inactive for a long time, so I will close this for now.
If you are still having problems, please reopen this issue or submit a new one.
